In [1]:
import numpy as np

def nander(matt,n,boolean):
    '''
     This function returns matrix that has columns which are powers of the input vector..
     
     INPUT: matt - List of Values for which we need Vander Matrix Prepared
            n - No of columns we need for the matrix
            boolean - True - the first column in the input vectore is power of N with reduced element wise for next column
                      False - the i-th output column in the input vector raised element-wise
                              to the power of N - i - 1
     OUTPUT: Matrix that has columns that are powers of input vector 
    '''
    # Variable to store one row of input vector raised element-wise to the power of N
    values = []
    # Variable to store the output in Matrix Form
    arr =[]

    for j in range(0,matt.size):
        #if boolean is True the first column in the input vectore is raised element wise to the power of N
        if(boolean):    
            #Loop to create the vectore based on the input arr / list
            for i in range(0,n):                
                # Appending the input arrays / list jth element to the power of i value 
                values.append(matt[j]**i)    
        #if boolean is False the first column in the input vectore is raised element wise to the power of N-i-1
        else:
            for i in range(n-1,-1,-1):
                # Appending the input arrays / list jth element to the power of i value 
                values.append(matt[j]**i)
        
        # Appending the rows of array in to the arr variable to form the Matrix
        arr.append(values)
        # Rest the Values to create new array list for the next element in the input array list
        values =[]
                
        
    return np.array(arr)


mat = np.array([1,2,3,4,5])
N = 4

print(f'Output using Vander Method : \n {np.vander(mat,N,False)}')

print(f'\nOutput using self written method : \n {nander(mat,N,False)}')

Output using Vander Method : 
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

Output using self written method : 
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
